name: Go CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Reinstall Go
      run: |
        sudo rm -rf /opt/hostedtoolcache/go
        curl -LO https://go.dev/dl/go1.23.11.linux-amd64.tar.gz
        sudo tar -C /usr/local -xzf go1.23.11.linux-amd64.tar.gz
        export PATH="/usr/local/go/bin:$PATH"
        go version
        go env

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.0

    - name: Run lint
      run: golangci-lint run ./...

    - name: Run tests with coverage
      run: go test -v -coverprofile=coverage.out ./internal/... ./skyline/...

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: coverage.out
        fail_ci_if_error: true