name: Go CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
        check-latest: true

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-forcefix-${{ hashFiles('**/go.mod') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install golangci-lint from source
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.55.0

    - name: Clean Go build cache
      run: go clean -cache -modcache

    - name: Remove Go build and module cache directories
      run: rm -rf ~/.cache/go-build ~/go/pkg/mod

    - name: Show golangci-lint config
      run: cat .golangci.yml

    - name: Run lint
      run: golangci-lint run --config=.golangci.yml --disable=typecheck --disable=staticcheck --disable=unused --disable=gosimple --disable=stylecheck --disable=varcheck --disable=structcheck --disable=ineffassign --disable=deadcode --disable=errcheck ./...

    - name: Run tests with coverage
      run: go test -v -coverprofile=coverage.out ./internal/... ./skyline/...

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: coverage.out
        fail_ci_if_error: true